[package]
name = "yad"
version = "0.3.1"
authors = ["agvantibo", "timgit0"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random-string = "1.0"
walkdir = "2"
dirs = "4.0"
fork = "0.1"
